package mux

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/adibhanna/tsm/internal/session"
)

// TestOpenManifestProjectStyle verifies that OpenManifest works with
// manifests generated by the project package (multiple workspaces,
// each with splits, project:branch naming).
func TestOpenManifestProjectStyle(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv("TSM_DIR", tmpDir)

	mock := &mockBackend{}
	orch := &Orchestrator{
		Backend: mock,
		SessCfg: session.Config{
			SocketDir: filepath.Join(tmpDir),
			LogDir:    filepath.Join(tmpDir, "logs"),
		},
	}

	// Simulate what project.Expand produces: one manifest per worktree,
	// each with an agent surface + git split.
	manifests := []*Manifest{
		{
			Name:    "app:main",
			Version: 1,
			Startup: "app:main",
			Surface: []ManifestSurface{
				{
					Name:    "dev",
					Session: "app:main",
					Cwd:     "/dev/app-main",
					Command: "claude",
					Split: []ManifestSplit{
						{
							Name:      "git",
							Session:   "app:main:git",
							Direction: "right",
							Cwd:       "/dev/app-main",
							Command:   "lazygit",
						},
					},
				},
			},
		},
		{
			Name:    "app:feat-auth",
			Version: 1,
			Startup: "app:feat-auth",
			Surface: []ManifestSurface{
				{
					Name:    "dev",
					Session: "app:feat-auth",
					Cwd:     "/dev/app-feat",
					Command: "claude",
					Split: []ManifestSplit{
						{
							Name:      "git",
							Session:   "app:feat-auth:git",
							Direction: "right",
							Cwd:       "/dev/app-feat",
							Command:   "lazygit",
						},
					},
				},
			},
		},
	}

	// Open each manifest like cmdProjectOpen does.
	for _, m := range manifests {
		err := orch.OpenManifest(m)
		// SpawnDaemon will fail in test env, but backend calls should be made.
		if err != nil {
			// Verify workspace was created before the session spawn failure.
			found := false
			for _, c := range mock.calls {
				if strings.Contains(c, "CreateWorkspace:"+m.Name) || strings.Contains(c, "SelectWorkspace:") {
					found = true
					break
				}
			}
			if !found {
				t.Errorf("manifest %q: expected workspace creation, got calls: %v", m.Name, mock.calls)
			}
			continue
		}
	}

	// Verify that workspaces were created for both manifests.
	var createCalls []string
	for _, c := range mock.calls {
		if strings.HasPrefix(c, "CreateWorkspace:") {
			createCalls = append(createCalls, c)
		}
	}
	// At minimum we should see workspace creation attempts for both.
	if len(createCalls) == 0 {
		t.Error("expected at least one CreateWorkspace call")
	}
}

// TestOpenManifestReuseExistingWorkspace verifies that if a workspace
// already exists, OpenManifest selects it instead of creating a new one.
func TestOpenManifestReuseExistingWorkspace(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv("TSM_DIR", tmpDir)

	mock := &mockBackend{
		workspaces: []Workspace{
			{ID: "workspace:42", Name: "app:main"},
		},
	}
	orch := &Orchestrator{
		Backend: mock,
		SessCfg: session.Config{
			SocketDir: filepath.Join(tmpDir),
			LogDir:    filepath.Join(tmpDir, "logs"),
		},
	}

	m := &Manifest{
		Name:    "app:main",
		Version: 1,
		Surface: []ManifestSurface{
			{Name: "dev", Session: "app:main"},
		},
	}

	_ = orch.OpenManifest(m)

	// Should have selected the existing workspace, not created a new one.
	for _, c := range mock.calls {
		if strings.HasPrefix(c, "CreateWorkspace:") {
			t.Errorf("should not create workspace when it exists, got: %s", c)
		}
	}

	hasSelect := false
	for _, c := range mock.calls {
		if c == "SelectWorkspace:workspace:42" {
			hasSelect = true
		}
	}
	if !hasSelect {
		t.Errorf("expected SelectWorkspace:workspace:42, got calls: %v", mock.calls)
	}
}

// TestManifestValidationWithProjectNames ensures that project-style
// names with colons pass manifest validation.
func TestManifestValidationWithProjectNames(t *testing.T) {
	m := &Manifest{
		Name:    "app:main",
		Version: 1,
		Surface: []ManifestSurface{
			{
				Name:    "dev",
				Session: "app:main",
				Split: []ManifestSplit{
					{Name: "git", Session: "app:main:git", Direction: "right"},
				},
			},
		},
	}

	if err := validateManifest(m); err != nil {
		t.Errorf("project-style manifest should be valid, got: %v", err)
	}
}
